import numpy as np
import pandas as pd
from astropy.timeseries import LombScargle
from scipy.interpolate import interp1d
from george import kernels
import george
import scipy.optimize as op



info = {'LPV':{'kernel':kernels.CosineKernel(np.log(1))+
                        kernels.Matern32Kernel(15),
               'p0':[1, 15], 
               'n_phs': np.inf,
               'p_range': [1, 500],
               'fit_binned': False,
               'gp_opt': False,
               'p0_period': lambda x: np.log10(x),
               'example': 'OGLE-BLG-LPV-048338',
                 'exp_period': 250.4,
                 'gp_opt_s_param': 1},
        'RRLYR':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 1.5], 
                 'n_phs': 10,
                 'p_range': [0.001, 1],
                 'fit_binned': True,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log10(1/x),
                 'example': 'OGLE-BLG-RRLYR-03350',
                 'exp_period': 0.51484451,
                 'gp_opt_s_param': 1},
        'DSCT':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 1.5], 
                 'n_phs': 10,
                 'p_range': [0.001, 0.5],
                 'fit_binned': False,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log10(1/x),
                 'example': 'OGLE-BLG-DSCT-00697',
                 'exp_period': 0.110287,
                 'gp_opt_s_param': 1},
        'ECL':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(0.5),
                 'p0':[1, 1.5], 
                 'n_phs': 5,
                 'p_range': [0.001, 1],
                 'fit_binned': False,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log10(1/x),
                 'example': 'OGLE-BLG-ECL-000013',
                 'exp_period': 0.2138646,
                 'gp_opt_s_param': .01},
        'ELL':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 0.1], 
                 'n_phs': 10,
                 'p_range': [0.001, 10],
                 'fit_binned': True,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log10(1/x),
                 'example': 'OGLE-BLG-ELL-000008',
                 'exp_period': 0.2130577,
                 'gp_opt_s_param': 1},
        'T2CEP':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 1.5], 
                 'n_phs': 10,
                 'p_range': [0.01, 30],
                 'fit_binned': False,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log10(1/x),
                 'example': 'OGLE-BLG-T2CEP-0078',
                 'exp_period': 16.7107943,
                 'gp_opt_s_param': 1},
        'CEP':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 0.1], 
                 'n_phs': 10,
                 'p_range': [0.001, 10],
                 'fit_binned': True,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log10(1/x),
                 'example': 'OGLE-BLG-CEP-019',
                 'exp_period': 0.2865322,
                 'gp_opt_s_param': 1},
        'HB':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
              'p0':[1, 15], 
              'n_phs': 3,
              'p_range': [100, 500],
              'fit_binned': False,
              'gp_opt': True,
              'p0_period': lambda x: np.log10(x),
              'example': 'OGLE-BLG-HB-0011',
              'exp_period': 354.453,
              'gp_opt_s_param': 1}
        }