import numpy as np
import pandas as pd
from astropy.timeseries import LombScargle
from scipy.interpolate import interp1d
from george import kernels
import george
import scipy.optimize as op

"""
Parameters of the Gaussian Processes are tuned for each category separately. These include preprocessing parameters, parameters of the kernel, and metric thresholds along with physical parameters of the systems.

kernel: Defining the kernel
p0: an initial set of parameters for the kernel. Note that the first parameter will be replaced by the known period of the system.
p_range: Range of periods for that category based on papers.
count_per_bins: 
"""

info = {'LPV':{'kernel':kernels.CosineKernel(np.log(1))+
                        kernels.Matern32Kernel(1.5),
               'p0':[1, 15], 
               'n_phs': np.inf,
               'p_range': [1, 500],
               'fit_binned': False,
               'count_per_bins':1000,
               'gp_opt': False,
               'p0_period': lambda x: np.log(x),
               'example': 'OGLE-BLG-LPV-048338',
               'exp_period': 250.4,
               'gp_opt_s_param': 3,
               'metric_threshold': 100,
               'metric_threshold_std': 500},
        'RRLYR':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(0),
                 'p0':[1, 0], 
                 'n_phs': 5,
                 'p_range': [0.001, 1],
                 'fit_binned': True,
                 'count_per_bins':150,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log(x),
                 'example': 'OGLE-BLG-RRLYR-03350',
                 'exp_period': 0.51484451,
                 'gp_opt_s_param': 5,
                 'metric_threshold': 0.01,
                 'metric_threshold_std': 0.01},
        'DSCT':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 1.5], 
                 'n_phs': 10,
                 'p_range': [0.001, 0.5],
                 'fit_binned': True,
                 'count_per_bins':50,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log(x),
                 'example': 'OGLE-BLG-DSCT-00697',
                 'exp_period': 0.110287,
                 'gp_opt_s_param': 1,
                 'metric_threshold': 0.01,
                 'metric_threshold_std': 0.01},
        'ECL':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(0.5),
                 'p0':[1, 1.5], 
                 'n_phs': 5,
                 'p_range': [0.001, 1],
                 'fit_binned': False,
                 'count_per_bins':50,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log(x),
                 'example': 'OGLE-BLG-ECL-100098',
                 'exp_period': 0.2138646,
                 'gp_opt_s_param': .1,
                 'metric_threshold': 0.01,
                 'metric_threshold_std': 0.05},
        'ELL':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 0.1], 
                 'n_phs': 7,
                 'p_range': [1, 500],
                 'fit_binned': True,
                 'count_per_bins':50,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log(x),
                 'example': 'OGLE-BLG-ELL-000008',
                 'exp_period': 0.2130577,
                 'gp_opt_s_param': 1,
                 'metric_threshold': 0.03,
                 'metric_threshold_std': 0.25},
        'T2CEP':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 1.5], 
                 'n_phs': 8,
                 'p_range': [0.01, 30],
                 'fit_binned': True,
                 'count_per_bins':50,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log(x),
                 'example': 'OGLE-BLG-T2CEP-0078',
                 'exp_period': 16.7107943,
                 'gp_opt_s_param': 1,
                 'metric_threshold': 0.01,
                 'metric_threshold_std': 0.01},
        'CEP':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(1.5),
                 'p0':[1, 0.1], 
                 'n_phs': 7,
                 'p_range': [0.001, 10],
                 'fit_binned': True,
                 'count_per_bins':50,
                 'gp_opt': True,
                 'p0_period': lambda x: np.log(x),
                 'example': 'OGLE-BLG-CEP-019',
                 'exp_period': 0.2865322,
                 'gp_opt_s_param': 1,
                 'metric_threshold': 0.02,
                 'metric_threshold_std': 0.02},
        'HB':{'kernel':kernels.CosineKernel(np.log(1))+kernels.Matern32Kernel(.15),
              'p0':[1, .15], 
              'n_phs': 4,
              'p_range': [100, 500],
              'fit_binned': True,
              'count_per_bins':100,
              'gp_opt': True,
              'p0_period': lambda x: np.log(x),
              'example': 'OGLE-BLG-HB-0011',
              'exp_period': 354.453,
              'gp_opt_s_param': 1,
              'metric_threshold': 6e-6,
              'metric_threshold_std': 0.1
             },
        'CV':{'kernel':kernels.Product(kernels.ConstantKernel(2.0), kernels.Matern32Kernel(5.0)),
              'p0':[2.0, 5.0], 
              'n_phs': np.inf,
              'p_range': [100, 500],
              'fit_binned': False,
              'count_per_bins':100,
              'gp_opt': True,
              'p0_period': np.nan,
              'example': 'OGLE-BLG-HB-0011',
              'exp_period': 354.453,
              'gp_opt_s_param': 1,
              'metric_threshold': 0,
              'metric_threshold_std': 0
             },
        'DN':{'kernel':kernels.Product(kernels.ConstantKernel(2.0), kernels.Matern32Kernel(5.0)),
              'p0':[3.0, 2.0], 
              'n_phs': np.inf,
              'p_range': [100, 500],
              'fit_binned': False,
              'count_per_bins':100,
              'gp_opt': True,
              'p0_period': np.nan,
              'example': 'OGLE-BLG-HB-0011',
              'exp_period': 354.453,
              'gp_opt_s_param': 1,
              'metric_threshold': 0,
              'metric_threshold_std': 0
             },
        'Be':{'kernel':kernels.Product(kernels.ConstantKernel(2), kernels.Matern52Kernel(5.0)),
              'p0':[3, 2.0], 
              'n_phs': np.inf,
              'p_range': [100, 500],
              'fit_binned': False,
              'count_per_bins':100,
              'gp_opt': True,
              'p0_period': np.nan,
              'example': 'OGLE-BLG-HB-0011',
              'exp_period': 354.453,
              'gp_opt_s_param': 2,
              'metric_threshold': 0,
              'metric_threshold_std': 0
             },
        'Flares_TESS':{'kernel':kernels.Product(kernels.ConstantKernel(3.0), kernels.Matern32Kernel(1)),
              'p0':[3, 2], 
              'n_phs': np.inf,
              'p_range': [100, 500],
              'fit_binned': False,
              'count_per_bins':100,
              'gp_opt': True,
              'p0_period': np.nan,
              'example': 'OGLE-BLG-HB-0011',
              'exp_period': 354.453,
              'gp_opt_s_param': 3,
              'metric_threshold': 0,
              'metric_threshold_std': 0
             }
        }